[package]
name = "mini_http"
version = "0.1.0"
authors = ["James Kominick <james.kominick@gmail.com>"]

[dependencies]
error-chain = "0.11"
threadpool = "1"
num_cpus = "1"
mio = "0.6"
slab = "0.4"
httparse = "1"
http = "0.1"
log = "0.3"

[dev-dependencies]
env_logger = "0.4"

